#!/bin/bash
# Converter for GitHub -> Subversion Repositories

# CPR : Jd Daniel :: Ehime-ken
# MOD : 2009-01-27 @ 11:25:06
# VER : Version 2.1.6b

root='@foo.com'

# Assumnes /usr/bin/awk
/bin/cat authors | awk -v r=$root '{print $1" <" $1 r ">"}'