#!/bin/bash
# WARC File assembler
 
# CPR : Jd Daniel :: Ehime-ken
# MOD : 2013-19-09 @ 12:22:43

clear; #set -x #debug

function BLUE() {
  echo -e '\n\E[37;44m'"\033[1m${1}\033[0m\n"
}

function GREEN() {
  echo -e '\n\E[37;42m'"\033[1m${1}\033[0m\n"
}

function RED() {
  echo -e '\n\E[37;41m'"\033[1m${1}\033[0m\n"
}

# early var declaration
declare -r FILENAME="$1"
declare -i USED=0

CDIR='/var/www/warcserver.dev' # `pwd`
DATE=($(date +"%Y-%d-%m"))
TIME=($(date +"%T"))

  if [ ! -f "${FILENAME}" ]; then
    \RED 'File does not exist, terminating....'
    tput sgr0 # reset
    exit
  fi

  \BLUE 'Reading input as array....'

  declare -a ARRAY
  declare -i ELEM=0

  ARRAY=($(cat "$FILENAME"))

  while [ $ELEM -le $((${#ARRAY[@]} - 1)) ]
  do

    cd $CDIR # move back to homepath

    PROPERDOM=$(echo ${ARRAY[$ELEM]} | grep -P '(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)')

    if [ $PROPERDOM ]; then

      # test the site 
      curl -s --head ${ARRAY[$ELEM]} | head -n 1 | grep "HTTP/1.[01] [23].." > /dev/null

      declare -i EXISTS=$?

      if [ '0' == $EXISTS ]; then

        echo -e "\tHIT: ${DOMAIN}"
        echo -e "\tArchive DIR: ${DATE}-${ARRAY[$ELEM]}"

        mkdir -p archive/${DATE}-${ARRAY[$ELEM]} && cd archive/${DATE}-${ARRAY[$ELEM]}

        \BLUE 'Starting ARC compression...'

        wget "${ARRAY[$ELEM]}" -r -l INF -k -p --no-check-certificate --strict-comments --warc-file="${DATE}-${ARRAY[$ELEM]}"

        hash CutyCapt 2>/dev/null || { 
          \GREEN "Attempting to install CutyCapt...."
          
            wget https://raw.github.com/ehime/bash-tools/master/cutycapt-installer-RHEL.sh
            chmod +x cutycapt-installer-RHEL.sh

            # run it
            bash cutycapt-installer-RHEL.sh
        }

        CutyCapt --url="${ARRAY[$ELEM]}" --out=example.png

        ((USED++))
      fi

    fi

    ((ELEM++))
  done

\BLUE "Used: ${USED}/${#ARRAY[@]} elements...."